### ISSUE TITLE
one error when running run_rlzoo.oy

### ISSUE THREAD

**Issue by hanbaoan123** [tensorlayer/RLzoo#17]
Traceback (most recent call last):
  File "D:/Anaconda3/Lib/site-packages/rlzoo/run_rlzoo.py", line 30, in <module>
    alg_params, learn_params = call_default_params(env, EnvType, AlgName)
  File "D:\Anaconda3\Lib\site-packages\rlzoo\common\utils.py", line 131, in call_default_params
    default_seed)  # need manually set seed in the main script if default_seed = False
  File "D:\Anaconda3\Lib\site-packages\rlzoo\algorithms\sac\default.py", line 43, in classic_control
    soft_q_net1 = QNetwork(env.observation_space, env.action_space,
NameError: name 'QNetwork' is not defined

**Comment by quantumiracle** [comment]
Sorry, I cannot reproduce your error. I guess it may be a version problem, could you please clone and install the latest version of rlzoo to see if you still have the problem?

The 'QNetwork' is defined in `rlzoo/common/value_networks.py` as a class, you can also manually import it in the `rlzoo/algorithms/sac/default.py`.
