### ISSUE TITLE
ImportError: cannot import name 'ArmActionMode' 

### ISSUE THREAD

**Issue by Leilasjd** [tensorlayer/RLzoo#45]
hi, I have run (rlzoo/interactive/main.ipynb ) and I got this error 
`ImportError: cannot import name 'ArmActionMode' `
I did the solution that was suggested in #43 but now I get a new error and the problem isn't solved.
the error is `action_shape() missing 1 required positional argument: 'scene'`
what should I do?

**Comment by quantumiracle** [comment]
Hi,

I think it is a dependency problem regarding the version of  RLBench or PyRep. Since the RLzoo repo is developed 3 years ago, the dependencies might have updated after that. I suggest to try down-grade the dependencies. I also need some time to take a look at this problem.

btw, which env are you using?

**Comment by Leilasjd** [comment]
Thank you for your quick response
I also tried with the older version of **RLBench==1.0.6** mentioned in #15 but this time I got the following error

`(myrlzoo) leila@pc:~/Downloads/RLzoo-master/rlzoo$  cd /home/leila/Downloads/RLzoo-master/rlzoo ; /usr/bin/env /home/leila/myrlzoo/bin/python3 /home/leila/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 37875 -- /home/leila/Downloads/RLzoo-master/rlzoo/run_rlzoo.py 
2022-12-17 15:35:42.600126: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/leila/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/:/home/leila/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/
2022-12-17 15:35:42.600205: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/leila/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/:/home/leila/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/
2022-12-17 15:35:42.600215: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-12-17 15:35:43.291645: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/leila/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/:/home/leila/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/
2022-12-17 15:35:43.291665: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-17 15:35:43.291682: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (pc): /proc/driver/nvidia/version does not exist
2022-12-17 15:35:43.292027: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-12-17 15:35:43.318402: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3597610000 Hz
2022-12-17 15:35:43.319116: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5645c8154c20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-12-17 15:35:43.319153: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Env ID PickUpCup Exists!
Traceback (most recent call last):
  File "/home/leila/Downloads/RLzoo-master/rlzoo/run_rlzoo.py", line 29, in <module>
    env = build_env(EnvName, EnvType)
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlzoo/common/env_wrappers.py", line 71, in build_env
    reward_shaping, stack, **kwargs)
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlzoo/common/env_wrappers.py", line 118, in _make_env
    env = RLBenchEnv(env_id) if state_type is None else RLBenchEnv(env_id, state_type)
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlzoo/common/build_rlbench_env.py", line 66, in __init__
    _, obs = self.task.reset()
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlbench/task_environment.py", line 82, in reset
    randomly_place=not self._static_positions)
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlbench/backend/scene.py", line 107, in init_episode
    self._active_task.validate()
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlbench/backend/task.py", line 248, in validate
    self._waypoints = self._get_waypoints()
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlbench/backend/task.py", line 374, in _get_waypoints
    feasible, way_i = self._feasible(waypoints)
  File "/home/leila/myrlzoo/lib/python3.7/site-packages/rlbench/backend/task.py", line 330, in _feasible
    path.set_to_end(allow_force_mode=False)
TypeError: set_to_end() got an unexpected keyword argument 'allow_force_mode'`

and i tried PickUpCup and ReachTarget env.
I also, use these packages:

CoppeliaSim==4.1.0
PyRep==4.1.0.3
RLBench==1.0.6
Python 3.7.7

Also, I could not find and install old versions of PyRep and I haven't GPU and I want to use CPU only.
